Solution added
Inzilbeth/SPbU3 pull request #1
Opened 2020-09-03 17:57 UTC by Inzilbeth

2020-09-03 18:41 UTC, yurii-litvinov requested changes
Пока что по ECTS-ной шкале было бы 3 балла из 4, хотя многие замечания не ошибки, а скорее рекомендации.

2020-09-03 18:41 UTC, yurii-litvinov commented on Homework1/Task1/MatrixMultiplication/Matrix.cs
> +        public int Columns { get; set; }
public-сеттер у этих свойств вызывает удивление, а отсутствие комментариев не даёт его развеять. Не уверен, что их вообще стоит отдельно хранить, matrixArray ведь знает свой размер по обоим измерениям.

2020-09-03 18:41 UTC, yurii-litvinov commented on Homework1/Task1/MatrixMultiplication/Matrix.cs
> +            var random = new Random((int)DateTime.Now.Ticks);
Он же, кажется, и так инициализируется таймером

2020-09-03 18:41 UTC, yurii-litvinov commented on Homework1/Task1/MatrixMultiplication/Matrix.cs
> +                    Console.Write($"{matrixArray[i, j]} ");
В интерполяции строк можно указывать форматные спецификаторы ширины поля, чтобы матрица выглядела посимпатичнее. См. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

2020-09-03 18:41 UTC, yurii-litvinov commented on Homework1/Task1/MatrixMultiplication/Matrix.cs
> +        }
Это обсудили, стоит ограничить число потоков, просто поровну поделив строки между ними

2020-09-03 18:41 UTC, yurii-litvinov commented on Homework1/Task1/MatrixMultiplication/Matrix.cs
> +            return true;
Если obj не матрица, то true? Даже если null? Мм.

2020-09-03 18:41 UTC, yurii-litvinov commented on Homework1/Task1/MatrixMultiplication/Parser.cs
> +            using (var streamReader = new StreamReader(path))
Тут using закрывается в самом конце метода, так что лучше было `using var streamReader = new StreamReader(path);` и дальше без фигурных скобок и лишнего отступа

2020-09-03 18:41 UTC, yurii-litvinov commented on Homework1/Task1/MatrixMultiplicationTests/MatrixMultiplicationTests.cs
> +        private Matrix ExpectedResult;
А поля именуются со строчной, даже в тестах

2020-09-03 18:41 UTC, yurii-litvinov commented on Homework1/Task1/MatrixMultiplicationTests/Tools.cs
> +        }
А есть же File.WriteAllText. То же с Read. Такие утилиты придумали до Вас

2020-09-03 18:41 UTC, yurii-litvinov commented on Homework1/Task1/Task1ConsoleApp/Program.cs
> +                var res = Matrix.MultiThreadedMultiply(a, b);
Компилятор не ругается на неиспользуемую переменную?

2020-09-03 18:56 UTC, Inzilbeth commented on Homework1/Task1/MatrixMultiplication/Matrix.cs
> +            return true;
А если методу в качестве параметра передать null объект, разве не вызовется ArgumentNullException?

2020-09-04 08:27 UTC, yurii-litvinov approved these changes
Да, теперь всё отлично, 4 балла.

2020-09-06 11:09 UTC, merged