Homework4task1
Inzilbeth/SPbU3 pull request #4
Opened 2020-10-16 18:16 UTC by Inzilbeth

2020-12-06 18:49 UTC, yurii-litvinov requested changes

2020-12-06 18:49 UTC, yurii-litvinov commented on Homework4/Task1/FTPTests/FTPTests.cs
> +                server.Stop();
Если client.List бросит исключение, то мы сюда не попадём уже и сервер никто не остановит.

2020-12-06 18:49 UTC, yurii-litvinov commented on Homework4/Task1/FTPTests/FTPTests.cs
> +            });
Так оно до завершения теста не успеет выполниться. Стоило её подождать, а вообще, async-тесты тоже вполне себе должны работать.

2020-12-06 18:49 UTC, yurii-litvinov commented on Homework4/Task1/FTPTests/FTPTests.cs
> +        public void SimoltaneousRequestsTest()
Sim**u**ltaneousRequestsTest

2020-12-06 18:49 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Client.cs
> +        public async Task Start()
Это должно быть не здесь, это лучше в Main-е делать. Потому что по идее этот же клиент будет нужен в GUIшном варианте, для него CLI смысла не имеет

2020-12-06 18:49 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Client.cs
> +            var writer = new StreamWriter(client.GetStream()) { AutoFlush = true };
Они тоже IDisposable, надо их объявлять как using var

2020-12-06 18:49 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Client.cs
> +            using (var fileStream = new FileStream(pathTo + fileName, FileMode.CreateNew))
Можно было через обычный using var, чтобы без лишних скобок

2020-12-06 18:49 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Program.cs
> +            var client = new Client("127.0.0.1", 9999);
Тут стоило получать IP/порт как args и как раз тут реализовать CLI (ведь Main --- это как раз то место, где стоит держать всё взаимодействие с пользователем, чтобы настоящие классы этим не занимались).

2020-12-06 18:49 UTC, yurii-litvinov commented on Homework4/Task1/Task1Server/Program.cs
> +            var server = new Server(9999);
Тут тоже, правильнее было получать порт как аргумент командной строки

2020-12-06 18:49 UTC, yurii-litvinov commented on Homework4/Task1/Task1Server/Server.cs
> +                    var client = await listener.AcceptTcpClientAsync();
TcpClient тоже IDisposable, но тут нельзя его просто как using var объявлять — он закроется, возможно, ещё до того, как потоку обработки запроса передадут управление. Надо сам клиент передавать в тот поток и там тут же брать на него using, чтобы по окончанию обработки запроса он корректно закрылся.

2021-01-02 12:08 UTC, yurii-litvinov requested changes
Какая-то беда с async-ами и task-ами в тестах, см. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/. Правда, прочитайте и разберитесь, это, наверное, процентов 70 всего современного многопоточного программирования, причём не только в .NET

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/FTPTests/FTPTests.cs
> +        public async Task ListFunctionalityTest()
Видите, какой гнев вызвал async у GitHub Actions? Потому что async Вы написали, а await перед client.List нет, и блокируете поток с тестом до получения Result. Что kind of defeats the purpose.

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/FTPTests/FTPTests.cs
> +            client.Stop();
Я бы хотя бы для клиента using использовал --- а то вдруг что-то пойдёт не так и Stop не вызовется. А чтобы и сервер остановить, обернул бы всё в try/finally. Иначе из-за одного сломанного теста сервер будет занимать порт и другие тесты, возможно, не смогут выполниться (хотя им вроде всё равно к какому серверу подключаться, но всё же)

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/FTPTests/FTPTests.cs
> +            var response = client.List("Example\\testFolder").Result;
Тут тоже можно было вместо .Result написать await, тест сделать async, и это было бы идеологически правильнее, хотя по сути бы ничего не изменилось

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/FTPTests/FTPTests.cs
> +            await Task.Run(async () =>
Мне кажется, это вообще не нужно. await Task.Run --- это "исполни следующий кусок кода в возможно другом потоке, без всякой видимой на то причины" --- ведь ничего параллельно не делается больше.

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Client.cs
> +        public async Task Start() => Connect();
Тут то же самое, async на самом деле не более чем "разрешает await-ы" внутри тела метода. Нет асинхронности --- нет радости.

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Client.cs
> +            var writer = new StreamWriter(client.GetStream()) { AutoFlush = true };
Напоминаю. Да, закрывающийся client закроет поток и освободит порт, но вообще надо давать всем IDisposable шанс исполнить свой Dispose, потому что у них, вообще говоря, могут быть свои какие-то внутренние ресурсы, которые надо финализировать.

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Program.cs
> +                throw new ArgumentException();
Лучше какую-то более дружелюбную диагностику выводить. И с int.Parse тоже может не сложиться, и тоже по-хорошему надо внятно об этом пользователю сказать

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Program.cs
> +                    if (input != null)
Надо фигурные скобки вокруг тела

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Program.cs
> +                                foreach (var e in res.Item2)
А ведь можно давать адекватные имена элементам кортежа, https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples#tuple-field-names

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/Task1Server/Program.cs
> +                port = int.Parse(args[1]);
Мм, а это работает?

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/Task1Server/RequestHandler.cs
> +            await writer.WriteLineAsync($"{size}");
Согласно протоколу из условия, после размера должен быть пробел, а не перевод строки

2021-01-02 12:08 UTC, yurii-litvinov commented on Homework4/Task1/Task1Server/Server.cs
> +        public async Task Start()
Тут тоже печаль с async-ом

2021-01-05 09:31 UTC, yurii-litvinov approved these changes
Комментарии к коммитам ужасны :) Но вообще, стало лучше, с async/await теперь почти всё правильно.

2021-01-05 09:31 UTC, yurii-litvinov commented on Homework4/Task1/FTPTests/FTPTests.cs
> +            Task.Run(async () =>
Остался загадочный Task.Run в конце метода, который никто не await-ит

2021-01-05 09:31 UTC, yurii-litvinov commented on Homework4/Task1/FTPTests/FTPTests.cs
> +                     (_, list) = client.List("Example\\testFolder").Result;
А тут ещё и .Result. То ли недоразбирались, то ли не хватило терпения везде исправить :)

2021-01-05 09:31 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Client.cs
> +        public void Start() => Connect();
На самом деле, не думаю, что это вообще надо теперь

2021-01-05 09:31 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Client.cs
> +            client = new TcpClient(server, port);
Подключение суть длительная операция, и если уж мы дизайним красивую асинхронную абстракцию, стоило бы это делать в отдельном потоке, через await Task.Run. Или, что лучше, https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.connectasync?view=net-5.0

2021-01-05 09:31 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Client.cs
> +            using var reader = new StreamReader(client.GetStream());
А тут тоже можно await using вроде

2021-01-05 13:18 UTC, Inzilbeth commented on Homework4/Task1/Task1Client/Client.cs
> +            using var reader = new StreamReader(client.GetStream());
Компилятор ругается, нельзя вроде как

2021-01-06 08:09 UTC, yurii-litvinov approved these changes
Ага, теперь в целом всё ок

2021-01-06 08:09 UTC, yurii-litvinov commented on Homework4/Task1/Task1Client/Program.cs
> +            client.Connect();
Оно говорит, что тут теперь тоже надо await-ить, раз Connect стал асинхронным. Иначе мы можем начать посылать запросы ещё до того, как подключение установится.

2021-09-09 19:28 UTC, merged