Homework5task1
Inzilbeth/SPbU3 pull request #6
Opened 2020-11-10 21:01 UTC by Inzilbeth

2020-11-10 21:02 UTC, Inzilbeth commented
Тесты и CI поправлю

2020-12-06 14:49 UTC, yurii-litvinov requested changes

2020-12-06 14:49 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/MyNUnit - Backup.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Этот файл, кажется, не нужен

2020-12-06 14:49 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/MyNUnit.cs
> +            => GetAssemblyPaths(path).Select(Assembly.LoadFrom).SelectMany(a => a.ExportedTypes).Where(t => t.IsClass);
Assembly.LoadFrom тоже стоит параллельно делать, загрузка сборки может быть относительно трудоёмкой, и она хорошо параллелится.

2020-12-06 14:49 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/MyNUnit.cs
> +        /// <returns>A collcection of paths.</returns>
collcection, опечатка

2020-12-06 14:49 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/MyNUnit.cs
> +                }
Сами тесты тоже надо параллельно запускать, а то если у нас все тесты в одном классе (как в большинстве домашек, кстати), то толку от всего остального распараллеливания ноль

2020-12-06 14:49 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/MyNUnit.cs
> +            if (attribute.IsIgnored)
Не уверен, что для игнорированного теста стоит создавать экземпляр. Ведь конструктор может иметь побочные эффекты, которые станут неожиданностью для пользователя.

2020-12-06 14:49 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/MyNUnit.cs
> +                    if (testInfo.IsIgnored == true)
Не стоит сравниваться с булевыми константами, лучше просто `if (testInfo.IsIgnored)`

2020-12-06 14:49 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/Utilities/ClassMethods.cs
> +        public ConcurrentQueue<MethodInfo> AfterClassTestMethods;
Паблик-поля запрещены, даже если очень хочется. Тем более в языке, где есть свойства

2020-12-06 14:49 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/Utilities/TestInfo.cs
> +        public string IgnoranceReason { get; private set; }
"Ignorance" внезапно переводится как "неведение". Тут правильнее IgnoreReason или IgnoringReason

2020-12-06 14:49 UTC, yurii-litvinov commented on Homework5/Task1/Task1Tests/MyNUnitTests.cs
> +            Assert.AreEqual(null, failInfo.ExpectedException);
Assert.IsNull лучше

2020-12-06 14:49 UTC, yurii-litvinov commented on Homework5/Task1/Test1/Test1.csproj
> +    <ProjectReference Include="..\MyNUnit\MyNUnit.csproj" />
Тестовый проект не должен ссылаться сразу на всё, вместе с раннером. Стоит атрибуты вынести в отдельную сборку, чтобы тестовый проект линковать только к ней и не тащить в тесты лишних зависимостей

2020-12-09 17:23 UTC, yurii-litvinov approved these changes
Теперь всё круто, зачтена

2020-12-09 17:23 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/MyNUnit.cs
> +            testResults = new ConcurrentDictionary<Type, ConcurrentBag<TestInfo>>();
Кажется, можно было прямо в месте объявления полей их инициализировать

2020-12-09 17:23 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/MyNUnit.cs
> +                stopwatch.Stop();
Можно было последними строками try и сatch тогда таймер не останавливать, всё равно это первое, что сделается в finally

2020-12-09 17:23 UTC, yurii-litvinov commented on Homework5/Task1/MyNUnit/MyNUnit.cs
> +            => method.Invoke(instance, null);
Я бы сказал, что если эти методы упали, тест стоит отметить как не проваленный, а не запустившийся, со стектрейсом исключения --- это тоже важный аспект диагностики. Тут же Вы пользовательский код запускаете, пользователь творит что хочет.

2021-01-07 12:30 UTC, merged